version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: ./api
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/kudwa_pnl
      - CORS_ORIGIN=http://localhost:5173
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    command: npm start

  web:
    build: ./web
    environment:
      - VITE_API_BASE=http://localhost:4000/api/v1
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  mongo-data:
